package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFLogPollsDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_polls.id_poll
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer idPoll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_polls.id_member
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer idMember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1log_polls.id_choice
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer idChoice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_polls.id_poll
	 * @return  the value of smf_1log_polls.id_poll
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getIdPoll() {
		return idPoll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_polls.id_poll
	 * @param idPoll  the value for smf_1log_polls.id_poll
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setIdPoll(Integer idPoll) {
		this.idPoll = idPoll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_polls.id_member
	 * @return  the value of smf_1log_polls.id_member
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getIdMember() {
		return idMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_polls.id_member
	 * @param idMember  the value for smf_1log_polls.id_member
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setIdMember(Integer idMember) {
		this.idMember = idMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1log_polls.id_choice
	 * @return  the value of smf_1log_polls.id_choice
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getIdChoice() {
		return idChoice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1log_polls.id_choice
	 * @param idChoice  the value for smf_1log_polls.id_choice
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setIdChoice(Integer idChoice) {
		this.idChoice = idChoice;
	}
}