package com.zfgc.zfgbb.migrator.smf.dbo;

import java.util.ArrayList;
import java.util.List;

public class SMFLogPollsDbExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public SMFLogPollsDbExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdPollIsNull() {
			addCriterion("id_poll is null");
			return (Criteria) this;
		}

		public Criteria andIdPollIsNotNull() {
			addCriterion("id_poll is not null");
			return (Criteria) this;
		}

		public Criteria andIdPollEqualTo(Integer value) {
			addCriterion("id_poll =", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollNotEqualTo(Integer value) {
			addCriterion("id_poll <>", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollGreaterThan(Integer value) {
			addCriterion("id_poll >", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_poll >=", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollLessThan(Integer value) {
			addCriterion("id_poll <", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollLessThanOrEqualTo(Integer value) {
			addCriterion("id_poll <=", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollIn(List<Integer> values) {
			addCriterion("id_poll in", values, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollNotIn(List<Integer> values) {
			addCriterion("id_poll not in", values, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollBetween(Integer value1, Integer value2) {
			addCriterion("id_poll between", value1, value2, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollNotBetween(Integer value1, Integer value2) {
			addCriterion("id_poll not between", value1, value2, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdMemberIsNull() {
			addCriterion("id_member is null");
			return (Criteria) this;
		}

		public Criteria andIdMemberIsNotNull() {
			addCriterion("id_member is not null");
			return (Criteria) this;
		}

		public Criteria andIdMemberEqualTo(Integer value) {
			addCriterion("id_member =", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberNotEqualTo(Integer value) {
			addCriterion("id_member <>", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberGreaterThan(Integer value) {
			addCriterion("id_member >", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_member >=", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberLessThan(Integer value) {
			addCriterion("id_member <", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberLessThanOrEqualTo(Integer value) {
			addCriterion("id_member <=", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberIn(List<Integer> values) {
			addCriterion("id_member in", values, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberNotIn(List<Integer> values) {
			addCriterion("id_member not in", values, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberBetween(Integer value1, Integer value2) {
			addCriterion("id_member between", value1, value2, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberNotBetween(Integer value1, Integer value2) {
			addCriterion("id_member not between", value1, value2, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdChoiceIsNull() {
			addCriterion("id_choice is null");
			return (Criteria) this;
		}

		public Criteria andIdChoiceIsNotNull() {
			addCriterion("id_choice is not null");
			return (Criteria) this;
		}

		public Criteria andIdChoiceEqualTo(Integer value) {
			addCriterion("id_choice =", value, "idChoice");
			return (Criteria) this;
		}

		public Criteria andIdChoiceNotEqualTo(Integer value) {
			addCriterion("id_choice <>", value, "idChoice");
			return (Criteria) this;
		}

		public Criteria andIdChoiceGreaterThan(Integer value) {
			addCriterion("id_choice >", value, "idChoice");
			return (Criteria) this;
		}

		public Criteria andIdChoiceGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_choice >=", value, "idChoice");
			return (Criteria) this;
		}

		public Criteria andIdChoiceLessThan(Integer value) {
			addCriterion("id_choice <", value, "idChoice");
			return (Criteria) this;
		}

		public Criteria andIdChoiceLessThanOrEqualTo(Integer value) {
			addCriterion("id_choice <=", value, "idChoice");
			return (Criteria) this;
		}

		public Criteria andIdChoiceIn(List<Integer> values) {
			addCriterion("id_choice in", values, "idChoice");
			return (Criteria) this;
		}

		public Criteria andIdChoiceNotIn(List<Integer> values) {
			addCriterion("id_choice not in", values, "idChoice");
			return (Criteria) this;
		}

		public Criteria andIdChoiceBetween(Integer value1, Integer value2) {
			addCriterion("id_choice between", value1, value2, "idChoice");
			return (Criteria) this;
		}

		public Criteria andIdChoiceNotBetween(Integer value1, Integer value2) {
			addCriterion("id_choice not between", value1, value2, "idChoice");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smf_1log_polls
     *
     * @mbg.generated do_not_delete_during_merge Wed Oct 15 23:02:11 EDT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}