package com.zfgc.zfgbb.migrator.smf.dbo;

import java.util.Date;
import java.time.LocalDate;

public class SMFMembersDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.id_member
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer idMember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.member_name
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String memberName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.date_registered
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer dateRegistered;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.posts
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer posts;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.id_group
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer idGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.lngfile
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String lngfile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.last_login
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer lastLogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.real_name
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.instant_messages
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer instantMessages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.unread_messages
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer unreadMessages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.passwd
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String passwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.email_address
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String emailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.personal_text
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String personalText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.gender
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.birthdate
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private LocalDate birthdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.website_title
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String websiteTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.website_url
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String websiteUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.location
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.icq
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String icq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.aim
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String aim;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.yim
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String yim;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.msn
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String msn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.hide_email
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Boolean hideEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.show_online
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Boolean showOnline;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.time_format
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String timeFormat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.time_offset
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Float timeOffset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.avatar
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.pm_email_notify
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte pmEmailNotify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.karma_bad
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer karmaBad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.karma_good
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer karmaGood;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.usertitle
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String usertitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.notify_announcements
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte notifyAnnouncements;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.notify_regularity
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte notifyRegularity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.notify_send_body
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte notifySendBody;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.notify_types
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte notifyTypes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.member_ip
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String memberIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.member_ip2
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String memberIp2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.secret_question
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String secretQuestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.secret_answer
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String secretAnswer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.id_theme
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte idTheme;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.is_activated
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte isActivated;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.validation_code
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String validationCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.id_msg_last_visit
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer idMsgLastVisit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.additional_groups
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String additionalGroups;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.smiley_set
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String smileySet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.id_post_group
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer idPostGroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.total_time_logged_in
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer totalTimeLoggedIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.password_salt
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String passwordSalt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.warnLevel
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte warnlevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.warning
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer warning;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.mod_prefs
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String modPrefs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.passwd_flood
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private String passwdFlood;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.new_pm
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte newPm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.pm_prefs
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Integer pmPrefs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.pm_receive_from
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte pmReceiveFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.is_spammer
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	private Byte isSpammer;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.id_member
	 * @return  the value of smf_1members.id_member
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getIdMember() {
		return idMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.id_member
	 * @param idMember  the value for smf_1members.id_member
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setIdMember(Integer idMember) {
		this.idMember = idMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.member_name
	 * @return  the value of smf_1members.member_name
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getMemberName() {
		return memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.member_name
	 * @param memberName  the value for smf_1members.member_name
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.date_registered
	 * @return  the value of smf_1members.date_registered
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getDateRegistered() {
		return dateRegistered;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.date_registered
	 * @param dateRegistered  the value for smf_1members.date_registered
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setDateRegistered(Integer dateRegistered) {
		this.dateRegistered = dateRegistered;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.posts
	 * @return  the value of smf_1members.posts
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getPosts() {
		return posts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.posts
	 * @param posts  the value for smf_1members.posts
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setPosts(Integer posts) {
		this.posts = posts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.id_group
	 * @return  the value of smf_1members.id_group
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getIdGroup() {
		return idGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.id_group
	 * @param idGroup  the value for smf_1members.id_group
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setIdGroup(Integer idGroup) {
		this.idGroup = idGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.lngfile
	 * @return  the value of smf_1members.lngfile
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getLngfile() {
		return lngfile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.lngfile
	 * @param lngfile  the value for smf_1members.lngfile
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setLngfile(String lngfile) {
		this.lngfile = lngfile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.last_login
	 * @return  the value of smf_1members.last_login
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getLastLogin() {
		return lastLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.last_login
	 * @param lastLogin  the value for smf_1members.last_login
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setLastLogin(Integer lastLogin) {
		this.lastLogin = lastLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.real_name
	 * @return  the value of smf_1members.real_name
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.real_name
	 * @param realName  the value for smf_1members.real_name
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.instant_messages
	 * @return  the value of smf_1members.instant_messages
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getInstantMessages() {
		return instantMessages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.instant_messages
	 * @param instantMessages  the value for smf_1members.instant_messages
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setInstantMessages(Integer instantMessages) {
		this.instantMessages = instantMessages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.unread_messages
	 * @return  the value of smf_1members.unread_messages
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getUnreadMessages() {
		return unreadMessages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.unread_messages
	 * @param unreadMessages  the value for smf_1members.unread_messages
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setUnreadMessages(Integer unreadMessages) {
		this.unreadMessages = unreadMessages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.passwd
	 * @return  the value of smf_1members.passwd
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getPasswd() {
		return passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.passwd
	 * @param passwd  the value for smf_1members.passwd
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.email_address
	 * @return  the value of smf_1members.email_address
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getEmailAddress() {
		return emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.email_address
	 * @param emailAddress  the value for smf_1members.email_address
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.personal_text
	 * @return  the value of smf_1members.personal_text
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getPersonalText() {
		return personalText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.personal_text
	 * @param personalText  the value for smf_1members.personal_text
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setPersonalText(String personalText) {
		this.personalText = personalText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.gender
	 * @return  the value of smf_1members.gender
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.gender
	 * @param gender  the value for smf_1members.gender
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setGender(Byte gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.birthdate
	 * @return  the value of smf_1members.birthdate
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public LocalDate getBirthdate() {
		return birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.birthdate
	 * @param birthdate  the value for smf_1members.birthdate
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setBirthdate(LocalDate birthdate) {
		this.birthdate = birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.website_title
	 * @return  the value of smf_1members.website_title
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getWebsiteTitle() {
		return websiteTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.website_title
	 * @param websiteTitle  the value for smf_1members.website_title
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setWebsiteTitle(String websiteTitle) {
		this.websiteTitle = websiteTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.website_url
	 * @return  the value of smf_1members.website_url
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getWebsiteUrl() {
		return websiteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.website_url
	 * @param websiteUrl  the value for smf_1members.website_url
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.location
	 * @return  the value of smf_1members.location
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.location
	 * @param location  the value for smf_1members.location
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.icq
	 * @return  the value of smf_1members.icq
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getIcq() {
		return icq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.icq
	 * @param icq  the value for smf_1members.icq
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setIcq(String icq) {
		this.icq = icq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.aim
	 * @return  the value of smf_1members.aim
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getAim() {
		return aim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.aim
	 * @param aim  the value for smf_1members.aim
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setAim(String aim) {
		this.aim = aim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.yim
	 * @return  the value of smf_1members.yim
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getYim() {
		return yim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.yim
	 * @param yim  the value for smf_1members.yim
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setYim(String yim) {
		this.yim = yim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.msn
	 * @return  the value of smf_1members.msn
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getMsn() {
		return msn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.msn
	 * @param msn  the value for smf_1members.msn
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setMsn(String msn) {
		this.msn = msn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.hide_email
	 * @return  the value of smf_1members.hide_email
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Boolean getHideEmail() {
		return hideEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.hide_email
	 * @param hideEmail  the value for smf_1members.hide_email
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setHideEmail(Boolean hideEmail) {
		this.hideEmail = hideEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.show_online
	 * @return  the value of smf_1members.show_online
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Boolean getShowOnline() {
		return showOnline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.show_online
	 * @param showOnline  the value for smf_1members.show_online
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setShowOnline(Boolean showOnline) {
		this.showOnline = showOnline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.time_format
	 * @return  the value of smf_1members.time_format
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getTimeFormat() {
		return timeFormat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.time_format
	 * @param timeFormat  the value for smf_1members.time_format
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setTimeFormat(String timeFormat) {
		this.timeFormat = timeFormat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.time_offset
	 * @return  the value of smf_1members.time_offset
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Float getTimeOffset() {
		return timeOffset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.time_offset
	 * @param timeOffset  the value for smf_1members.time_offset
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setTimeOffset(Float timeOffset) {
		this.timeOffset = timeOffset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.avatar
	 * @return  the value of smf_1members.avatar
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.avatar
	 * @param avatar  the value for smf_1members.avatar
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.pm_email_notify
	 * @return  the value of smf_1members.pm_email_notify
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getPmEmailNotify() {
		return pmEmailNotify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.pm_email_notify
	 * @param pmEmailNotify  the value for smf_1members.pm_email_notify
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setPmEmailNotify(Byte pmEmailNotify) {
		this.pmEmailNotify = pmEmailNotify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.karma_bad
	 * @return  the value of smf_1members.karma_bad
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getKarmaBad() {
		return karmaBad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.karma_bad
	 * @param karmaBad  the value for smf_1members.karma_bad
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setKarmaBad(Integer karmaBad) {
		this.karmaBad = karmaBad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.karma_good
	 * @return  the value of smf_1members.karma_good
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getKarmaGood() {
		return karmaGood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.karma_good
	 * @param karmaGood  the value for smf_1members.karma_good
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setKarmaGood(Integer karmaGood) {
		this.karmaGood = karmaGood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.usertitle
	 * @return  the value of smf_1members.usertitle
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getUsertitle() {
		return usertitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.usertitle
	 * @param usertitle  the value for smf_1members.usertitle
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setUsertitle(String usertitle) {
		this.usertitle = usertitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.notify_announcements
	 * @return  the value of smf_1members.notify_announcements
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getNotifyAnnouncements() {
		return notifyAnnouncements;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.notify_announcements
	 * @param notifyAnnouncements  the value for smf_1members.notify_announcements
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setNotifyAnnouncements(Byte notifyAnnouncements) {
		this.notifyAnnouncements = notifyAnnouncements;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.notify_regularity
	 * @return  the value of smf_1members.notify_regularity
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getNotifyRegularity() {
		return notifyRegularity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.notify_regularity
	 * @param notifyRegularity  the value for smf_1members.notify_regularity
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setNotifyRegularity(Byte notifyRegularity) {
		this.notifyRegularity = notifyRegularity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.notify_send_body
	 * @return  the value of smf_1members.notify_send_body
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getNotifySendBody() {
		return notifySendBody;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.notify_send_body
	 * @param notifySendBody  the value for smf_1members.notify_send_body
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setNotifySendBody(Byte notifySendBody) {
		this.notifySendBody = notifySendBody;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.notify_types
	 * @return  the value of smf_1members.notify_types
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getNotifyTypes() {
		return notifyTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.notify_types
	 * @param notifyTypes  the value for smf_1members.notify_types
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setNotifyTypes(Byte notifyTypes) {
		this.notifyTypes = notifyTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.member_ip
	 * @return  the value of smf_1members.member_ip
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getMemberIp() {
		return memberIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.member_ip
	 * @param memberIp  the value for smf_1members.member_ip
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setMemberIp(String memberIp) {
		this.memberIp = memberIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.member_ip2
	 * @return  the value of smf_1members.member_ip2
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getMemberIp2() {
		return memberIp2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.member_ip2
	 * @param memberIp2  the value for smf_1members.member_ip2
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setMemberIp2(String memberIp2) {
		this.memberIp2 = memberIp2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.secret_question
	 * @return  the value of smf_1members.secret_question
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getSecretQuestion() {
		return secretQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.secret_question
	 * @param secretQuestion  the value for smf_1members.secret_question
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setSecretQuestion(String secretQuestion) {
		this.secretQuestion = secretQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.secret_answer
	 * @return  the value of smf_1members.secret_answer
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getSecretAnswer() {
		return secretAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.secret_answer
	 * @param secretAnswer  the value for smf_1members.secret_answer
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setSecretAnswer(String secretAnswer) {
		this.secretAnswer = secretAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.id_theme
	 * @return  the value of smf_1members.id_theme
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getIdTheme() {
		return idTheme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.id_theme
	 * @param idTheme  the value for smf_1members.id_theme
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setIdTheme(Byte idTheme) {
		this.idTheme = idTheme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.is_activated
	 * @return  the value of smf_1members.is_activated
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getIsActivated() {
		return isActivated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.is_activated
	 * @param isActivated  the value for smf_1members.is_activated
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setIsActivated(Byte isActivated) {
		this.isActivated = isActivated;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.validation_code
	 * @return  the value of smf_1members.validation_code
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getValidationCode() {
		return validationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.validation_code
	 * @param validationCode  the value for smf_1members.validation_code
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setValidationCode(String validationCode) {
		this.validationCode = validationCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.id_msg_last_visit
	 * @return  the value of smf_1members.id_msg_last_visit
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getIdMsgLastVisit() {
		return idMsgLastVisit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.id_msg_last_visit
	 * @param idMsgLastVisit  the value for smf_1members.id_msg_last_visit
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setIdMsgLastVisit(Integer idMsgLastVisit) {
		this.idMsgLastVisit = idMsgLastVisit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.additional_groups
	 * @return  the value of smf_1members.additional_groups
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getAdditionalGroups() {
		return additionalGroups;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.additional_groups
	 * @param additionalGroups  the value for smf_1members.additional_groups
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setAdditionalGroups(String additionalGroups) {
		this.additionalGroups = additionalGroups;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.smiley_set
	 * @return  the value of smf_1members.smiley_set
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getSmileySet() {
		return smileySet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.smiley_set
	 * @param smileySet  the value for smf_1members.smiley_set
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setSmileySet(String smileySet) {
		this.smileySet = smileySet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.id_post_group
	 * @return  the value of smf_1members.id_post_group
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getIdPostGroup() {
		return idPostGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.id_post_group
	 * @param idPostGroup  the value for smf_1members.id_post_group
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setIdPostGroup(Integer idPostGroup) {
		this.idPostGroup = idPostGroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.total_time_logged_in
	 * @return  the value of smf_1members.total_time_logged_in
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getTotalTimeLoggedIn() {
		return totalTimeLoggedIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.total_time_logged_in
	 * @param totalTimeLoggedIn  the value for smf_1members.total_time_logged_in
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setTotalTimeLoggedIn(Integer totalTimeLoggedIn) {
		this.totalTimeLoggedIn = totalTimeLoggedIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.password_salt
	 * @return  the value of smf_1members.password_salt
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getPasswordSalt() {
		return passwordSalt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.password_salt
	 * @param passwordSalt  the value for smf_1members.password_salt
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setPasswordSalt(String passwordSalt) {
		this.passwordSalt = passwordSalt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.warnLevel
	 * @return  the value of smf_1members.warnLevel
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getWarnlevel() {
		return warnlevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.warnLevel
	 * @param warnlevel  the value for smf_1members.warnLevel
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setWarnlevel(Byte warnlevel) {
		this.warnlevel = warnlevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.warning
	 * @return  the value of smf_1members.warning
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getWarning() {
		return warning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.warning
	 * @param warning  the value for smf_1members.warning
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setWarning(Integer warning) {
		this.warning = warning;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.mod_prefs
	 * @return  the value of smf_1members.mod_prefs
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getModPrefs() {
		return modPrefs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.mod_prefs
	 * @param modPrefs  the value for smf_1members.mod_prefs
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setModPrefs(String modPrefs) {
		this.modPrefs = modPrefs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.passwd_flood
	 * @return  the value of smf_1members.passwd_flood
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public String getPasswdFlood() {
		return passwdFlood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.passwd_flood
	 * @param passwdFlood  the value for smf_1members.passwd_flood
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setPasswdFlood(String passwdFlood) {
		this.passwdFlood = passwdFlood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.new_pm
	 * @return  the value of smf_1members.new_pm
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getNewPm() {
		return newPm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.new_pm
	 * @param newPm  the value for smf_1members.new_pm
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setNewPm(Byte newPm) {
		this.newPm = newPm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.pm_prefs
	 * @return  the value of smf_1members.pm_prefs
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Integer getPmPrefs() {
		return pmPrefs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.pm_prefs
	 * @param pmPrefs  the value for smf_1members.pm_prefs
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setPmPrefs(Integer pmPrefs) {
		this.pmPrefs = pmPrefs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.pm_receive_from
	 * @return  the value of smf_1members.pm_receive_from
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getPmReceiveFrom() {
		return pmReceiveFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.pm_receive_from
	 * @param pmReceiveFrom  the value for smf_1members.pm_receive_from
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setPmReceiveFrom(Byte pmReceiveFrom) {
		this.pmReceiveFrom = pmReceiveFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.is_spammer
	 * @return  the value of smf_1members.is_spammer
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public Byte getIsSpammer() {
		return isSpammer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.is_spammer
	 * @param isSpammer  the value for smf_1members.is_spammer
	 * @mbg.generated  Mon Oct 06 19:58:23 EDT 2025
	 */
	public void setIsSpammer(Byte isSpammer) {
		this.isSpammer = isSpammer;
	}
}