package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFMembersDbWithBLOBs extends SMFMembersDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.buddy_list
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	private String buddyList;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.pm_ignore_list
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	private String pmIgnoreList;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.message_labels
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	private String messageLabels;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.signature
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	private String signature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.ignore_boards
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	private String ignoreBoards;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1members.openid_uri
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	private String openidUri;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.buddy_list
	 * @return  the value of smf_1members.buddy_list
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public String getBuddyList() {
		return buddyList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.buddy_list
	 * @param buddyList  the value for smf_1members.buddy_list
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public void setBuddyList(String buddyList) {
		this.buddyList = buddyList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.pm_ignore_list
	 * @return  the value of smf_1members.pm_ignore_list
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public String getPmIgnoreList() {
		return pmIgnoreList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.pm_ignore_list
	 * @param pmIgnoreList  the value for smf_1members.pm_ignore_list
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public void setPmIgnoreList(String pmIgnoreList) {
		this.pmIgnoreList = pmIgnoreList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.message_labels
	 * @return  the value of smf_1members.message_labels
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public String getMessageLabels() {
		return messageLabels;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.message_labels
	 * @param messageLabels  the value for smf_1members.message_labels
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public void setMessageLabels(String messageLabels) {
		this.messageLabels = messageLabels;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.signature
	 * @return  the value of smf_1members.signature
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public String getSignature() {
		return signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.signature
	 * @param signature  the value for smf_1members.signature
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public void setSignature(String signature) {
		this.signature = signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.ignore_boards
	 * @return  the value of smf_1members.ignore_boards
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public String getIgnoreBoards() {
		return ignoreBoards;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.ignore_boards
	 * @param ignoreBoards  the value for smf_1members.ignore_boards
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public void setIgnoreBoards(String ignoreBoards) {
		this.ignoreBoards = ignoreBoards;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1members.openid_uri
	 * @return  the value of smf_1members.openid_uri
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public String getOpenidUri() {
		return openidUri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1members.openid_uri
	 * @param openidUri  the value for smf_1members.openid_uri
	 * @mbg.generated  Wed Sep 10 23:29:55 EDT 2025
	 */
	public void setOpenidUri(String openidUri) {
		this.openidUri = openidUri;
	}
}