package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFPollChoicesDb extends SMFPollChoicesDbKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1poll_choices.label
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private String label;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1poll_choices.votes
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Short votes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1poll_choices.label
	 * @return  the value of smf_1poll_choices.label
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1poll_choices.label
	 * @param label  the value for smf_1poll_choices.label
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setLabel(String label) {
		this.label = label;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1poll_choices.votes
	 * @return  the value of smf_1poll_choices.votes
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Short getVotes() {
		return votes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1poll_choices.votes
	 * @param votes  the value for smf_1poll_choices.votes
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setVotes(Short votes) {
		this.votes = votes;
	}
}