package com.zfgc.zfgbb.migrator.smf.dbo;

public class SMFPollsDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.id_poll
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer idPoll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.ID_TOPIC
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer idTopic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.question
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private String question;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.voting_locked
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Boolean votingLocked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.max_votes
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer maxVotes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.expire_time
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer expireTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.hide_results
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Boolean hideResults;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.change_vote
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Boolean changeVote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.id_member
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer idMember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.poster_name
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private String posterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.guest_vote
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Boolean guestVote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.num_guest_voters
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer numGuestVoters;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column smf_1polls.reset_poll
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	private Integer resetPoll;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.id_poll
	 * @return  the value of smf_1polls.id_poll
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getIdPoll() {
		return idPoll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.id_poll
	 * @param idPoll  the value for smf_1polls.id_poll
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setIdPoll(Integer idPoll) {
		this.idPoll = idPoll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.ID_TOPIC
	 * @return  the value of smf_1polls.ID_TOPIC
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getIdTopic() {
		return idTopic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.ID_TOPIC
	 * @param idTopic  the value for smf_1polls.ID_TOPIC
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setIdTopic(Integer idTopic) {
		this.idTopic = idTopic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.question
	 * @return  the value of smf_1polls.question
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public String getQuestion() {
		return question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.question
	 * @param question  the value for smf_1polls.question
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setQuestion(String question) {
		this.question = question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.voting_locked
	 * @return  the value of smf_1polls.voting_locked
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Boolean getVotingLocked() {
		return votingLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.voting_locked
	 * @param votingLocked  the value for smf_1polls.voting_locked
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setVotingLocked(Boolean votingLocked) {
		this.votingLocked = votingLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.max_votes
	 * @return  the value of smf_1polls.max_votes
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getMaxVotes() {
		return maxVotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.max_votes
	 * @param maxVotes  the value for smf_1polls.max_votes
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setMaxVotes(Integer maxVotes) {
		this.maxVotes = maxVotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.expire_time
	 * @return  the value of smf_1polls.expire_time
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getExpireTime() {
		return expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.expire_time
	 * @param expireTime  the value for smf_1polls.expire_time
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setExpireTime(Integer expireTime) {
		this.expireTime = expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.hide_results
	 * @return  the value of smf_1polls.hide_results
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Boolean getHideResults() {
		return hideResults;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.hide_results
	 * @param hideResults  the value for smf_1polls.hide_results
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setHideResults(Boolean hideResults) {
		this.hideResults = hideResults;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.change_vote
	 * @return  the value of smf_1polls.change_vote
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Boolean getChangeVote() {
		return changeVote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.change_vote
	 * @param changeVote  the value for smf_1polls.change_vote
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setChangeVote(Boolean changeVote) {
		this.changeVote = changeVote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.id_member
	 * @return  the value of smf_1polls.id_member
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getIdMember() {
		return idMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.id_member
	 * @param idMember  the value for smf_1polls.id_member
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setIdMember(Integer idMember) {
		this.idMember = idMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.poster_name
	 * @return  the value of smf_1polls.poster_name
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public String getPosterName() {
		return posterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.poster_name
	 * @param posterName  the value for smf_1polls.poster_name
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setPosterName(String posterName) {
		this.posterName = posterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.guest_vote
	 * @return  the value of smf_1polls.guest_vote
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Boolean getGuestVote() {
		return guestVote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.guest_vote
	 * @param guestVote  the value for smf_1polls.guest_vote
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setGuestVote(Boolean guestVote) {
		this.guestVote = guestVote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.num_guest_voters
	 * @return  the value of smf_1polls.num_guest_voters
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getNumGuestVoters() {
		return numGuestVoters;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.num_guest_voters
	 * @param numGuestVoters  the value for smf_1polls.num_guest_voters
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setNumGuestVoters(Integer numGuestVoters) {
		this.numGuestVoters = numGuestVoters;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column smf_1polls.reset_poll
	 * @return  the value of smf_1polls.reset_poll
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Integer getResetPoll() {
		return resetPoll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column smf_1polls.reset_poll
	 * @param resetPoll  the value for smf_1polls.reset_poll
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setResetPoll(Integer resetPoll) {
		this.resetPoll = resetPoll;
	}
}