package com.zfgc.zfgbb.migrator.smf.dbo;

import java.util.ArrayList;
import java.util.List;

public class SMFPollsDbExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public SMFPollsDbExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdPollIsNull() {
			addCriterion("id_poll is null");
			return (Criteria) this;
		}

		public Criteria andIdPollIsNotNull() {
			addCriterion("id_poll is not null");
			return (Criteria) this;
		}

		public Criteria andIdPollEqualTo(Integer value) {
			addCriterion("id_poll =", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollNotEqualTo(Integer value) {
			addCriterion("id_poll <>", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollGreaterThan(Integer value) {
			addCriterion("id_poll >", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_poll >=", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollLessThan(Integer value) {
			addCriterion("id_poll <", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollLessThanOrEqualTo(Integer value) {
			addCriterion("id_poll <=", value, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollIn(List<Integer> values) {
			addCriterion("id_poll in", values, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollNotIn(List<Integer> values) {
			addCriterion("id_poll not in", values, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollBetween(Integer value1, Integer value2) {
			addCriterion("id_poll between", value1, value2, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdPollNotBetween(Integer value1, Integer value2) {
			addCriterion("id_poll not between", value1, value2, "idPoll");
			return (Criteria) this;
		}

		public Criteria andIdTopicIsNull() {
			addCriterion("ID_TOPIC is null");
			return (Criteria) this;
		}

		public Criteria andIdTopicIsNotNull() {
			addCriterion("ID_TOPIC is not null");
			return (Criteria) this;
		}

		public Criteria andIdTopicEqualTo(Integer value) {
			addCriterion("ID_TOPIC =", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicNotEqualTo(Integer value) {
			addCriterion("ID_TOPIC <>", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicGreaterThan(Integer value) {
			addCriterion("ID_TOPIC >", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID_TOPIC >=", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicLessThan(Integer value) {
			addCriterion("ID_TOPIC <", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicLessThanOrEqualTo(Integer value) {
			addCriterion("ID_TOPIC <=", value, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicIn(List<Integer> values) {
			addCriterion("ID_TOPIC in", values, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicNotIn(List<Integer> values) {
			addCriterion("ID_TOPIC not in", values, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicBetween(Integer value1, Integer value2) {
			addCriterion("ID_TOPIC between", value1, value2, "idTopic");
			return (Criteria) this;
		}

		public Criteria andIdTopicNotBetween(Integer value1, Integer value2) {
			addCriterion("ID_TOPIC not between", value1, value2, "idTopic");
			return (Criteria) this;
		}

		public Criteria andQuestionIsNull() {
			addCriterion("question is null");
			return (Criteria) this;
		}

		public Criteria andQuestionIsNotNull() {
			addCriterion("question is not null");
			return (Criteria) this;
		}

		public Criteria andQuestionEqualTo(String value) {
			addCriterion("question =", value, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionNotEqualTo(String value) {
			addCriterion("question <>", value, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionGreaterThan(String value) {
			addCriterion("question >", value, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionGreaterThanOrEqualTo(String value) {
			addCriterion("question >=", value, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionLessThan(String value) {
			addCriterion("question <", value, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionLessThanOrEqualTo(String value) {
			addCriterion("question <=", value, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionLike(String value) {
			addCriterion("question like", value, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionNotLike(String value) {
			addCriterion("question not like", value, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionIn(List<String> values) {
			addCriterion("question in", values, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionNotIn(List<String> values) {
			addCriterion("question not in", values, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionBetween(String value1, String value2) {
			addCriterion("question between", value1, value2, "question");
			return (Criteria) this;
		}

		public Criteria andQuestionNotBetween(String value1, String value2) {
			addCriterion("question not between", value1, value2, "question");
			return (Criteria) this;
		}

		public Criteria andVotingLockedIsNull() {
			addCriterion("voting_locked is null");
			return (Criteria) this;
		}

		public Criteria andVotingLockedIsNotNull() {
			addCriterion("voting_locked is not null");
			return (Criteria) this;
		}

		public Criteria andVotingLockedEqualTo(Boolean value) {
			addCriterion("voting_locked =", value, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andVotingLockedNotEqualTo(Boolean value) {
			addCriterion("voting_locked <>", value, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andVotingLockedGreaterThan(Boolean value) {
			addCriterion("voting_locked >", value, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andVotingLockedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("voting_locked >=", value, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andVotingLockedLessThan(Boolean value) {
			addCriterion("voting_locked <", value, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andVotingLockedLessThanOrEqualTo(Boolean value) {
			addCriterion("voting_locked <=", value, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andVotingLockedIn(List<Boolean> values) {
			addCriterion("voting_locked in", values, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andVotingLockedNotIn(List<Boolean> values) {
			addCriterion("voting_locked not in", values, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andVotingLockedBetween(Boolean value1, Boolean value2) {
			addCriterion("voting_locked between", value1, value2, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andVotingLockedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("voting_locked not between", value1, value2, "votingLocked");
			return (Criteria) this;
		}

		public Criteria andMaxVotesIsNull() {
			addCriterion("max_votes is null");
			return (Criteria) this;
		}

		public Criteria andMaxVotesIsNotNull() {
			addCriterion("max_votes is not null");
			return (Criteria) this;
		}

		public Criteria andMaxVotesEqualTo(Integer value) {
			addCriterion("max_votes =", value, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andMaxVotesNotEqualTo(Integer value) {
			addCriterion("max_votes <>", value, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andMaxVotesGreaterThan(Integer value) {
			addCriterion("max_votes >", value, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andMaxVotesGreaterThanOrEqualTo(Integer value) {
			addCriterion("max_votes >=", value, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andMaxVotesLessThan(Integer value) {
			addCriterion("max_votes <", value, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andMaxVotesLessThanOrEqualTo(Integer value) {
			addCriterion("max_votes <=", value, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andMaxVotesIn(List<Integer> values) {
			addCriterion("max_votes in", values, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andMaxVotesNotIn(List<Integer> values) {
			addCriterion("max_votes not in", values, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andMaxVotesBetween(Integer value1, Integer value2) {
			addCriterion("max_votes between", value1, value2, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andMaxVotesNotBetween(Integer value1, Integer value2) {
			addCriterion("max_votes not between", value1, value2, "maxVotes");
			return (Criteria) this;
		}

		public Criteria andExpireTimeIsNull() {
			addCriterion("expire_time is null");
			return (Criteria) this;
		}

		public Criteria andExpireTimeIsNotNull() {
			addCriterion("expire_time is not null");
			return (Criteria) this;
		}

		public Criteria andExpireTimeEqualTo(Integer value) {
			addCriterion("expire_time =", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeNotEqualTo(Integer value) {
			addCriterion("expire_time <>", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeGreaterThan(Integer value) {
			addCriterion("expire_time >", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("expire_time >=", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeLessThan(Integer value) {
			addCriterion("expire_time <", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeLessThanOrEqualTo(Integer value) {
			addCriterion("expire_time <=", value, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeIn(List<Integer> values) {
			addCriterion("expire_time in", values, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeNotIn(List<Integer> values) {
			addCriterion("expire_time not in", values, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeBetween(Integer value1, Integer value2) {
			addCriterion("expire_time between", value1, value2, "expireTime");
			return (Criteria) this;
		}

		public Criteria andExpireTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("expire_time not between", value1, value2, "expireTime");
			return (Criteria) this;
		}

		public Criteria andHideResultsIsNull() {
			addCriterion("hide_results is null");
			return (Criteria) this;
		}

		public Criteria andHideResultsIsNotNull() {
			addCriterion("hide_results is not null");
			return (Criteria) this;
		}

		public Criteria andHideResultsEqualTo(Boolean value) {
			addCriterion("hide_results =", value, "hideResults");
			return (Criteria) this;
		}

		public Criteria andHideResultsNotEqualTo(Boolean value) {
			addCriterion("hide_results <>", value, "hideResults");
			return (Criteria) this;
		}

		public Criteria andHideResultsGreaterThan(Boolean value) {
			addCriterion("hide_results >", value, "hideResults");
			return (Criteria) this;
		}

		public Criteria andHideResultsGreaterThanOrEqualTo(Boolean value) {
			addCriterion("hide_results >=", value, "hideResults");
			return (Criteria) this;
		}

		public Criteria andHideResultsLessThan(Boolean value) {
			addCriterion("hide_results <", value, "hideResults");
			return (Criteria) this;
		}

		public Criteria andHideResultsLessThanOrEqualTo(Boolean value) {
			addCriterion("hide_results <=", value, "hideResults");
			return (Criteria) this;
		}

		public Criteria andHideResultsIn(List<Boolean> values) {
			addCriterion("hide_results in", values, "hideResults");
			return (Criteria) this;
		}

		public Criteria andHideResultsNotIn(List<Boolean> values) {
			addCriterion("hide_results not in", values, "hideResults");
			return (Criteria) this;
		}

		public Criteria andHideResultsBetween(Boolean value1, Boolean value2) {
			addCriterion("hide_results between", value1, value2, "hideResults");
			return (Criteria) this;
		}

		public Criteria andHideResultsNotBetween(Boolean value1, Boolean value2) {
			addCriterion("hide_results not between", value1, value2, "hideResults");
			return (Criteria) this;
		}

		public Criteria andChangeVoteIsNull() {
			addCriterion("change_vote is null");
			return (Criteria) this;
		}

		public Criteria andChangeVoteIsNotNull() {
			addCriterion("change_vote is not null");
			return (Criteria) this;
		}

		public Criteria andChangeVoteEqualTo(Boolean value) {
			addCriterion("change_vote =", value, "changeVote");
			return (Criteria) this;
		}

		public Criteria andChangeVoteNotEqualTo(Boolean value) {
			addCriterion("change_vote <>", value, "changeVote");
			return (Criteria) this;
		}

		public Criteria andChangeVoteGreaterThan(Boolean value) {
			addCriterion("change_vote >", value, "changeVote");
			return (Criteria) this;
		}

		public Criteria andChangeVoteGreaterThanOrEqualTo(Boolean value) {
			addCriterion("change_vote >=", value, "changeVote");
			return (Criteria) this;
		}

		public Criteria andChangeVoteLessThan(Boolean value) {
			addCriterion("change_vote <", value, "changeVote");
			return (Criteria) this;
		}

		public Criteria andChangeVoteLessThanOrEqualTo(Boolean value) {
			addCriterion("change_vote <=", value, "changeVote");
			return (Criteria) this;
		}

		public Criteria andChangeVoteIn(List<Boolean> values) {
			addCriterion("change_vote in", values, "changeVote");
			return (Criteria) this;
		}

		public Criteria andChangeVoteNotIn(List<Boolean> values) {
			addCriterion("change_vote not in", values, "changeVote");
			return (Criteria) this;
		}

		public Criteria andChangeVoteBetween(Boolean value1, Boolean value2) {
			addCriterion("change_vote between", value1, value2, "changeVote");
			return (Criteria) this;
		}

		public Criteria andChangeVoteNotBetween(Boolean value1, Boolean value2) {
			addCriterion("change_vote not between", value1, value2, "changeVote");
			return (Criteria) this;
		}

		public Criteria andIdMemberIsNull() {
			addCriterion("id_member is null");
			return (Criteria) this;
		}

		public Criteria andIdMemberIsNotNull() {
			addCriterion("id_member is not null");
			return (Criteria) this;
		}

		public Criteria andIdMemberEqualTo(Integer value) {
			addCriterion("id_member =", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberNotEqualTo(Integer value) {
			addCriterion("id_member <>", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberGreaterThan(Integer value) {
			addCriterion("id_member >", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberGreaterThanOrEqualTo(Integer value) {
			addCriterion("id_member >=", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberLessThan(Integer value) {
			addCriterion("id_member <", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberLessThanOrEqualTo(Integer value) {
			addCriterion("id_member <=", value, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberIn(List<Integer> values) {
			addCriterion("id_member in", values, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberNotIn(List<Integer> values) {
			addCriterion("id_member not in", values, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberBetween(Integer value1, Integer value2) {
			addCriterion("id_member between", value1, value2, "idMember");
			return (Criteria) this;
		}

		public Criteria andIdMemberNotBetween(Integer value1, Integer value2) {
			addCriterion("id_member not between", value1, value2, "idMember");
			return (Criteria) this;
		}

		public Criteria andPosterNameIsNull() {
			addCriterion("poster_name is null");
			return (Criteria) this;
		}

		public Criteria andPosterNameIsNotNull() {
			addCriterion("poster_name is not null");
			return (Criteria) this;
		}

		public Criteria andPosterNameEqualTo(String value) {
			addCriterion("poster_name =", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameNotEqualTo(String value) {
			addCriterion("poster_name <>", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameGreaterThan(String value) {
			addCriterion("poster_name >", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameGreaterThanOrEqualTo(String value) {
			addCriterion("poster_name >=", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameLessThan(String value) {
			addCriterion("poster_name <", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameLessThanOrEqualTo(String value) {
			addCriterion("poster_name <=", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameLike(String value) {
			addCriterion("poster_name like", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameNotLike(String value) {
			addCriterion("poster_name not like", value, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameIn(List<String> values) {
			addCriterion("poster_name in", values, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameNotIn(List<String> values) {
			addCriterion("poster_name not in", values, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameBetween(String value1, String value2) {
			addCriterion("poster_name between", value1, value2, "posterName");
			return (Criteria) this;
		}

		public Criteria andPosterNameNotBetween(String value1, String value2) {
			addCriterion("poster_name not between", value1, value2, "posterName");
			return (Criteria) this;
		}

		public Criteria andGuestVoteIsNull() {
			addCriterion("guest_vote is null");
			return (Criteria) this;
		}

		public Criteria andGuestVoteIsNotNull() {
			addCriterion("guest_vote is not null");
			return (Criteria) this;
		}

		public Criteria andGuestVoteEqualTo(Boolean value) {
			addCriterion("guest_vote =", value, "guestVote");
			return (Criteria) this;
		}

		public Criteria andGuestVoteNotEqualTo(Boolean value) {
			addCriterion("guest_vote <>", value, "guestVote");
			return (Criteria) this;
		}

		public Criteria andGuestVoteGreaterThan(Boolean value) {
			addCriterion("guest_vote >", value, "guestVote");
			return (Criteria) this;
		}

		public Criteria andGuestVoteGreaterThanOrEqualTo(Boolean value) {
			addCriterion("guest_vote >=", value, "guestVote");
			return (Criteria) this;
		}

		public Criteria andGuestVoteLessThan(Boolean value) {
			addCriterion("guest_vote <", value, "guestVote");
			return (Criteria) this;
		}

		public Criteria andGuestVoteLessThanOrEqualTo(Boolean value) {
			addCriterion("guest_vote <=", value, "guestVote");
			return (Criteria) this;
		}

		public Criteria andGuestVoteIn(List<Boolean> values) {
			addCriterion("guest_vote in", values, "guestVote");
			return (Criteria) this;
		}

		public Criteria andGuestVoteNotIn(List<Boolean> values) {
			addCriterion("guest_vote not in", values, "guestVote");
			return (Criteria) this;
		}

		public Criteria andGuestVoteBetween(Boolean value1, Boolean value2) {
			addCriterion("guest_vote between", value1, value2, "guestVote");
			return (Criteria) this;
		}

		public Criteria andGuestVoteNotBetween(Boolean value1, Boolean value2) {
			addCriterion("guest_vote not between", value1, value2, "guestVote");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersIsNull() {
			addCriterion("num_guest_voters is null");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersIsNotNull() {
			addCriterion("num_guest_voters is not null");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersEqualTo(Integer value) {
			addCriterion("num_guest_voters =", value, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersNotEqualTo(Integer value) {
			addCriterion("num_guest_voters <>", value, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersGreaterThan(Integer value) {
			addCriterion("num_guest_voters >", value, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersGreaterThanOrEqualTo(Integer value) {
			addCriterion("num_guest_voters >=", value, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersLessThan(Integer value) {
			addCriterion("num_guest_voters <", value, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersLessThanOrEqualTo(Integer value) {
			addCriterion("num_guest_voters <=", value, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersIn(List<Integer> values) {
			addCriterion("num_guest_voters in", values, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersNotIn(List<Integer> values) {
			addCriterion("num_guest_voters not in", values, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersBetween(Integer value1, Integer value2) {
			addCriterion("num_guest_voters between", value1, value2, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andNumGuestVotersNotBetween(Integer value1, Integer value2) {
			addCriterion("num_guest_voters not between", value1, value2, "numGuestVoters");
			return (Criteria) this;
		}

		public Criteria andResetPollIsNull() {
			addCriterion("reset_poll is null");
			return (Criteria) this;
		}

		public Criteria andResetPollIsNotNull() {
			addCriterion("reset_poll is not null");
			return (Criteria) this;
		}

		public Criteria andResetPollEqualTo(Integer value) {
			addCriterion("reset_poll =", value, "resetPoll");
			return (Criteria) this;
		}

		public Criteria andResetPollNotEqualTo(Integer value) {
			addCriterion("reset_poll <>", value, "resetPoll");
			return (Criteria) this;
		}

		public Criteria andResetPollGreaterThan(Integer value) {
			addCriterion("reset_poll >", value, "resetPoll");
			return (Criteria) this;
		}

		public Criteria andResetPollGreaterThanOrEqualTo(Integer value) {
			addCriterion("reset_poll >=", value, "resetPoll");
			return (Criteria) this;
		}

		public Criteria andResetPollLessThan(Integer value) {
			addCriterion("reset_poll <", value, "resetPoll");
			return (Criteria) this;
		}

		public Criteria andResetPollLessThanOrEqualTo(Integer value) {
			addCriterion("reset_poll <=", value, "resetPoll");
			return (Criteria) this;
		}

		public Criteria andResetPollIn(List<Integer> values) {
			addCriterion("reset_poll in", values, "resetPoll");
			return (Criteria) this;
		}

		public Criteria andResetPollNotIn(List<Integer> values) {
			addCriterion("reset_poll not in", values, "resetPoll");
			return (Criteria) this;
		}

		public Criteria andResetPollBetween(Integer value1, Integer value2) {
			addCriterion("reset_poll between", value1, value2, "resetPoll");
			return (Criteria) this;
		}

		public Criteria andResetPollNotBetween(Integer value1, Integer value2) {
			addCriterion("reset_poll not between", value1, value2, "resetPoll");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table smf_1polls
     *
     * @mbg.generated do_not_delete_during_merge Wed Oct 15 23:02:11 EDT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}