package com.zfgc.zfgbb.migrator.smf.mappers;

import com.zfgc.zfgbb.migrator.smf.dbo.SMFLogPollsDb;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFLogPollsDbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMFLogPollsDbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	long countByExample(SMFLogPollsDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int deleteByExample(SMFLogPollsDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int insert(SMFLogPollsDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int insertSelective(SMFLogPollsDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	List<SMFLogPollsDb> selectByExample(SMFLogPollsDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") SMFLogPollsDb row, @Param("example") SMFLogPollsDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1log_polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByExample(@Param("row") SMFLogPollsDb row, @Param("example") SMFLogPollsDbExample example);
}