package com.zfgc.zfgbb.migrator.smf.mappers;

import com.zfgc.zfgbb.migrator.smf.dbo.SMFMembersDb;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFMembersDbExample;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFMembersDbWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMFMembersDbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	long countByExample(SMFMembersDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int deleteByExample(SMFMembersDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int deleteByPrimaryKey(Integer idMember);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int insert(SMFMembersDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int insertSelective(SMFMembersDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	List<SMFMembersDbWithBLOBs> selectByExampleWithBLOBs(SMFMembersDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	List<SMFMembersDb> selectByExample(SMFMembersDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	SMFMembersDbWithBLOBs selectByPrimaryKey(Integer idMember);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") SMFMembersDbWithBLOBs row,
			@Param("example") SMFMembersDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int updateByExampleWithBLOBs(@Param("row") SMFMembersDbWithBLOBs row,
			@Param("example") SMFMembersDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int updateByExample(@Param("row") SMFMembersDb row, @Param("example") SMFMembersDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int updateByPrimaryKeySelective(SMFMembersDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int updateByPrimaryKeyWithBLOBs(SMFMembersDbWithBLOBs row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1members
	 * @mbg.generated  Mon Oct 06 19:58:24 EDT 2025
	 */
	int updateByPrimaryKey(SMFMembersDb row);
}