package com.zfgc.zfgbb.migrator.smf.mappers;

import com.zfgc.zfgbb.migrator.smf.dbo.SMFPollChoicesDb;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFPollChoicesDbExample;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFPollChoicesDbKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMFPollChoicesDbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	long countByExample(SMFPollChoicesDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int deleteByExample(SMFPollChoicesDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int deleteByPrimaryKey(SMFPollChoicesDbKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int insert(SMFPollChoicesDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int insertSelective(SMFPollChoicesDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	List<SMFPollChoicesDb> selectByExample(SMFPollChoicesDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	SMFPollChoicesDb selectByPrimaryKey(SMFPollChoicesDbKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") SMFPollChoicesDb row, @Param("example") SMFPollChoicesDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByExample(@Param("row") SMFPollChoicesDb row, @Param("example") SMFPollChoicesDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByPrimaryKeySelective(SMFPollChoicesDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1poll_choices
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByPrimaryKey(SMFPollChoicesDb row);
}