package com.zfgc.zfgbb.migrator.smf.mappers;

import com.zfgc.zfgbb.migrator.smf.dbo.SMFPollsDb;
import com.zfgc.zfgbb.migrator.smf.dbo.SMFPollsDbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SMFPollsDbMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	long countByExample(SMFPollsDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int deleteByExample(SMFPollsDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int deleteByPrimaryKey(Integer idPoll);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int insert(SMFPollsDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int insertSelective(SMFPollsDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	List<SMFPollsDb> selectByExample(SMFPollsDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	SMFPollsDb selectByPrimaryKey(Integer idPoll);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") SMFPollsDb row, @Param("example") SMFPollsDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByExample(@Param("row") SMFPollsDb row, @Param("example") SMFPollsDbExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByPrimaryKeySelective(SMFPollsDb row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table smf_1polls
	 * @mbg.generated  Sun Oct 19 16:54:44 EDT 2025
	 */
	int updateByPrimaryKey(SMFPollsDb row);
}