package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.EmailAddressDbo;
import com.zfgc.zfgbb.migrator.db.EmailAddressDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailAddressDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	long countByExample(EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	int deleteByExample(EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer emailAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	int insert(EmailAddressDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	int insertSelective(EmailAddressDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	List<EmailAddressDbo> selectByExample(EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	EmailAddressDbo selectByPrimaryKey(Integer emailAddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") EmailAddressDbo row, @Param("example") EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") EmailAddressDbo row, @Param("example") EmailAddressDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(EmailAddressDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.email_address
	 * @mbg.generated
	 */
	int updateByPrimaryKey(EmailAddressDbo row);
} 