package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.GenderLkupDbo;
import com.zfgc.zfgbb.migrator.db.GenderLkupDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GenderLkupDboMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    long countByExample(GenderLkupDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    int deleteByExample(GenderLkupDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    int deleteByPrimaryKey(Integer genderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    int insert(GenderLkupDbo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    int insertSelective(GenderLkupDbo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    List<GenderLkupDbo> selectByExample(GenderLkupDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    GenderLkupDbo selectByPrimaryKey(Integer genderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    int updateByExampleSelective(@Param("row") GenderLkupDbo row, @Param("example") GenderLkupDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    int updateByExample(@Param("row") GenderLkupDbo row, @Param("example") GenderLkupDboExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    int updateByPrimaryKeySelective(GenderLkupDbo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zfgbb.gender_lkup
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    int updateByPrimaryKey(GenderLkupDbo row);
}