package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.PollChoiceDbo;
import com.zfgc.zfgbb.migrator.db.PollChoiceDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollChoiceDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	long countByExample(PollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	int deleteByExample(PollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	int deleteByPrimaryKey(Integer pollChoiceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	int insert(PollChoiceDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	int insertSelective(PollChoiceDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	List<PollChoiceDbo> selectByExample(PollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	PollChoiceDbo selectByPrimaryKey(Integer pollChoiceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") PollChoiceDbo row, @Param("example") PollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	int updateByExample(@Param("row") PollChoiceDbo row, @Param("example") PollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	int updateByPrimaryKeySelective(PollChoiceDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	int updateByPrimaryKey(PollChoiceDbo row);
}