package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.PollDbo;
import com.zfgc.zfgbb.migrator.db.PollDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PollDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	long countByExample(PollDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	int deleteByExample(PollDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	int deleteByPrimaryKey(Integer pollId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	int insert(PollDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	int insertSelective(PollDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	List<PollDbo> selectByExample(PollDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	PollDbo selectByPrimaryKey(Integer pollId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	int updateByExampleSelective(@Param("row") PollDbo row, @Param("example") PollDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	int updateByExample(@Param("row") PollDbo row, @Param("example") PollDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	int updateByPrimaryKeySelective(PollDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	int updateByPrimaryKey(PollDbo row);
}