package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.UserContactInfoDbo;
import com.zfgc.zfgbb.migrator.db.UserContactInfoDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserContactInfoDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	long countByExample(UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	int deleteByExample(UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	int insert(UserContactInfoDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	int insertSelective(UserContactInfoDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	List<UserContactInfoDbo> selectByExample(UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	UserContactInfoDbo selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") UserContactInfoDbo row, @Param("example") UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") UserContactInfoDbo row, @Param("example") UserContactInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(UserContactInfoDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_contact_info
	 * @mbg.generated
	 */
	int updateByPrimaryKey(UserContactInfoDbo row);
} 