package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.UserBioInfoDbo;
import com.zfgc.zfgbb.migrator.db.UserBioInfoDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBioInfoDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	long countByExample(UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	int deleteByExample(UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	int insert(UserBioInfoDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	int insertSelective(UserBioInfoDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	List<UserBioInfoDbo> selectByExample(UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	UserBioInfoDbo selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") UserBioInfoDbo row, @Param("example") UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	int updateByExample(@Param("row") UserBioInfoDbo row, @Param("example") UserBioInfoDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	int updateByPrimaryKeySelective(UserBioInfoDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_bio_info
	 * @mbg.generated  Mon Oct 06 19:47:43 EDT 2025
	 */
	int updateByPrimaryKey(UserBioInfoDbo row);
}