package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.UserNotifSettingsDbo;
import com.zfgc.zfgbb.migrator.db.UserNotifSettingsDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserNotifSettingsDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	long countByExample(UserNotifSettingsDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	int deleteByExample(UserNotifSettingsDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	int insert(UserNotifSettingsDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	int insertSelective(UserNotifSettingsDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	List<UserNotifSettingsDbo> selectByExample(UserNotifSettingsDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	UserNotifSettingsDbo selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("row") UserNotifSettingsDbo row, @Param("example") UserNotifSettingsDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	int updateByExample(@Param("row") UserNotifSettingsDbo row, @Param("example") UserNotifSettingsDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(UserNotifSettingsDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_notif_settings
	 * @mbg.generated
	 */
	int updateByPrimaryKey(UserNotifSettingsDbo row);
} 