package com.zfgc.zfgbb.migrator.mappers;

import com.zfgc.zfgbb.migrator.db.UserPollChoiceDbo;
import com.zfgc.zfgbb.migrator.db.UserPollChoiceDboExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPollChoiceDboMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	long countByExample(UserPollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	int deleteByExample(UserPollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	int deleteByPrimaryKey(Integer userPollChoiceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	int insert(UserPollChoiceDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	int insertSelective(UserPollChoiceDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	List<UserPollChoiceDbo> selectByExample(UserPollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	UserPollChoiceDbo selectByPrimaryKey(Integer userPollChoiceId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	int updateByExampleSelective(@Param("row") UserPollChoiceDbo row,
			@Param("example") UserPollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	int updateByExample(@Param("row") UserPollChoiceDbo row, @Param("example") UserPollChoiceDboExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	int updateByPrimaryKeySelective(UserPollChoiceDbo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.user_poll_choice
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	int updateByPrimaryKey(UserPollChoiceDbo row);
}