package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

public class EmailAddressDbo extends AbstractPostgresDb {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.email_address.email_address_id
	 * @mbg.generated
	 */
	private Integer emailAddressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.email_address.email_address
	 * @mbg.generated
	 */
	private String emailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.email_address.created_ts
	 * @mbg.generated
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.email_address.updated_ts
	 * @mbg.generated
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.email_address.spammer_flag
	 * @mbg.generated
	 */
	private Boolean spammerFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.email_address.migration_hash
	 * @mbg.generated
	 */
	private String migrationHash;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.email_address.email_address_id
	 * @return  the value of zfgbb.email_address.email_address_id
	 * @mbg.generated
	 */
	public Integer getEmailAddressId() {
		return emailAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.email_address.email_address_id
	 * @param emailAddressId  the value for zfgbb.email_address.email_address_id
	 * @mbg.generated
	 */
	public void setEmailAddressId(Integer emailAddressId) {
		this.emailAddressId = emailAddressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.email_address.email_address
	 * @return  the value of zfgbb.email_address.email_address
	 * @mbg.generated
	 */
	public String getEmailAddress() {
		return emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.email_address.email_address
	 * @param emailAddress  the value for zfgbb.email_address.email_address
	 * @mbg.generated
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.email_address.created_ts
	 * @return  the value of zfgbb.email_address.created_ts
	 * @mbg.generated
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.email_address.created_ts
	 * @param createdTs  the value for zfgbb.email_address.created_ts
	 * @mbg.generated
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.email_address.updated_ts
	 * @return  the value of zfgbb.email_address.updated_ts
	 * @mbg.generated
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.email_address.updated_ts
	 * @param updatedTs  the value for zfgbb.email_address.updated_ts
	 * @mbg.generated
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.email_address.spammer_flag
	 * @return  the value of zfgbb.email_address.spammer_flag
	 * @mbg.generated
	 */
	public Boolean getSpammerFlag() {
		return spammerFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.email_address.spammer_flag
	 * @param spammerFlag  the value for zfgbb.email_address.spammer_flag
	 * @mbg.generated
	 */
	public void setSpammerFlag(Boolean spammerFlag) {
		this.spammerFlag = spammerFlag;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.email_address.migration_hash
	 * @return  the value of zfgbb.email_address.migration_hash
	 * @mbg.generated
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.email_address.migration_hash
	 * @param migrationHash  the value for zfgbb.email_address.migration_hash
	 * @mbg.generated
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal(
			emailAddress
			+ spammerFlag.toString()
		);
	}
} 