package com.zfgc.zfgbb.migrator.db;

import java.time.LocalDateTime;

public class GenderLkupDbo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.gender_lkup.gender_id
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    private Integer genderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.gender_lkup.code
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.gender_lkup.description
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.gender_lkup.seqno
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    private Integer seqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.gender_lkup.created_ts
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    private LocalDateTime createdTs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zfgbb.gender_lkup.updated_ts
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    private LocalDateTime updatedTs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.gender_lkup.gender_id
     *
     * @return the value of zfgbb.gender_lkup.gender_id
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public Integer getGenderId() {
        return genderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.gender_lkup.gender_id
     *
     * @param genderId the value for zfgbb.gender_lkup.gender_id
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public void setGenderId(Integer genderId) {
        this.genderId = genderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.gender_lkup.code
     *
     * @return the value of zfgbb.gender_lkup.code
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.gender_lkup.code
     *
     * @param code the value for zfgbb.gender_lkup.code
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.gender_lkup.description
     *
     * @return the value of zfgbb.gender_lkup.description
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.gender_lkup.description
     *
     * @param description the value for zfgbb.gender_lkup.description
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.gender_lkup.seqno
     *
     * @return the value of zfgbb.gender_lkup.seqno
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public Integer getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.gender_lkup.seqno
     *
     * @param seqno the value for zfgbb.gender_lkup.seqno
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public void setSeqno(Integer seqno) {
        this.seqno = seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.gender_lkup.created_ts
     *
     * @return the value of zfgbb.gender_lkup.created_ts
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public LocalDateTime getCreatedTs() {
        return createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.gender_lkup.created_ts
     *
     * @param createdTs the value for zfgbb.gender_lkup.created_ts
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public void setCreatedTs(LocalDateTime createdTs) {
        this.createdTs = createdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zfgbb.gender_lkup.updated_ts
     *
     * @return the value of zfgbb.gender_lkup.updated_ts
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public LocalDateTime getUpdatedTs() {
        return updatedTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zfgbb.gender_lkup.updated_ts
     *
     * @param updatedTs the value for zfgbb.gender_lkup.updated_ts
     *
     * @mbg.generated Sun Sep 21 17:49:18 EDT 2025
     */
    public void setUpdatedTs(LocalDateTime updatedTs) {
        this.updatedTs = updatedTs;
    }
}