package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

import lombok.Builder;

@Builder(toBuilder=true)
public class PollChoiceDbo extends AbstractPostgresDb {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll_choice.poll_choice_id
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	private Integer pollChoiceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll_choice.poll_id
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	private Integer pollId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll_choice.choice_text
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	private String choiceText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll_choice.active_flag
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	private Boolean activeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll_choice.votes
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	private Integer votes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll_choice.migration_hash
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	private String migrationHash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll_choice.created_ts
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll_choice.updated_ts
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll_choice.seqno
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	private Integer seqno;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll_choice.poll_choice_id
	 * @return  the value of zfgbb.poll_choice.poll_choice_id
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public Integer getPollChoiceId() {
		return pollChoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll_choice.poll_choice_id
	 * @param pollChoiceId  the value for zfgbb.poll_choice.poll_choice_id
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setPollChoiceId(Integer pollChoiceId) {
		this.pollChoiceId = pollChoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll_choice.poll_id
	 * @return  the value of zfgbb.poll_choice.poll_id
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public Integer getPollId() {
		return pollId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll_choice.poll_id
	 * @param pollId  the value for zfgbb.poll_choice.poll_id
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setPollId(Integer pollId) {
		this.pollId = pollId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll_choice.choice_text
	 * @return  the value of zfgbb.poll_choice.choice_text
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public String getChoiceText() {
		return choiceText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll_choice.choice_text
	 * @param choiceText  the value for zfgbb.poll_choice.choice_text
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setChoiceText(String choiceText) {
		this.choiceText = choiceText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll_choice.active_flag
	 * @return  the value of zfgbb.poll_choice.active_flag
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public Boolean getActiveFlag() {
		return activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll_choice.active_flag
	 * @param activeFlag  the value for zfgbb.poll_choice.active_flag
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setActiveFlag(Boolean activeFlag) {
		this.activeFlag = activeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll_choice.votes
	 * @return  the value of zfgbb.poll_choice.votes
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public Integer getVotes() {
		return votes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll_choice.votes
	 * @param votes  the value for zfgbb.poll_choice.votes
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setVotes(Integer votes) {
		this.votes = votes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll_choice.migration_hash
	 * @return  the value of zfgbb.poll_choice.migration_hash
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll_choice.migration_hash
	 * @param migrationHash  the value for zfgbb.poll_choice.migration_hash
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll_choice.created_ts
	 * @return  the value of zfgbb.poll_choice.created_ts
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll_choice.created_ts
	 * @param createdTs  the value for zfgbb.poll_choice.created_ts
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll_choice.updated_ts
	 * @return  the value of zfgbb.poll_choice.updated_ts
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll_choice.updated_ts
	 * @param updatedTs  the value for zfgbb.poll_choice.updated_ts
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll_choice.seqno
	 * @return  the value of zfgbb.poll_choice.seqno
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public Integer getSeqno() {
		return seqno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll_choice.seqno
	 * @param seqno  the value for zfgbb.poll_choice.seqno
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setSeqno(Integer seqno) {
		this.seqno = seqno;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal(
					this.choiceText +
					this.seqno.toString() +
					this.pollId.toString() +
					this.votes.toString() +
					this.activeFlag.toString()
				);
				
	}
}