package com.zfgc.zfgbb.migrator.db;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PollChoiceDboExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public PollChoiceDboExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPollChoiceIdIsNull() {
			addCriterion("poll_choice_id is null");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdIsNotNull() {
			addCriterion("poll_choice_id is not null");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdEqualTo(Integer value) {
			addCriterion("poll_choice_id =", value, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdNotEqualTo(Integer value) {
			addCriterion("poll_choice_id <>", value, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdGreaterThan(Integer value) {
			addCriterion("poll_choice_id >", value, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("poll_choice_id >=", value, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdLessThan(Integer value) {
			addCriterion("poll_choice_id <", value, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdLessThanOrEqualTo(Integer value) {
			addCriterion("poll_choice_id <=", value, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdIn(List<Integer> values) {
			addCriterion("poll_choice_id in", values, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdNotIn(List<Integer> values) {
			addCriterion("poll_choice_id not in", values, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdBetween(Integer value1, Integer value2) {
			addCriterion("poll_choice_id between", value1, value2, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollChoiceIdNotBetween(Integer value1, Integer value2) {
			addCriterion("poll_choice_id not between", value1, value2, "pollChoiceId");
			return (Criteria) this;
		}

		public Criteria andPollIdIsNull() {
			addCriterion("poll_id is null");
			return (Criteria) this;
		}

		public Criteria andPollIdIsNotNull() {
			addCriterion("poll_id is not null");
			return (Criteria) this;
		}

		public Criteria andPollIdEqualTo(Integer value) {
			addCriterion("poll_id =", value, "pollId");
			return (Criteria) this;
		}

		public Criteria andPollIdNotEqualTo(Integer value) {
			addCriterion("poll_id <>", value, "pollId");
			return (Criteria) this;
		}

		public Criteria andPollIdGreaterThan(Integer value) {
			addCriterion("poll_id >", value, "pollId");
			return (Criteria) this;
		}

		public Criteria andPollIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("poll_id >=", value, "pollId");
			return (Criteria) this;
		}

		public Criteria andPollIdLessThan(Integer value) {
			addCriterion("poll_id <", value, "pollId");
			return (Criteria) this;
		}

		public Criteria andPollIdLessThanOrEqualTo(Integer value) {
			addCriterion("poll_id <=", value, "pollId");
			return (Criteria) this;
		}

		public Criteria andPollIdIn(List<Integer> values) {
			addCriterion("poll_id in", values, "pollId");
			return (Criteria) this;
		}

		public Criteria andPollIdNotIn(List<Integer> values) {
			addCriterion("poll_id not in", values, "pollId");
			return (Criteria) this;
		}

		public Criteria andPollIdBetween(Integer value1, Integer value2) {
			addCriterion("poll_id between", value1, value2, "pollId");
			return (Criteria) this;
		}

		public Criteria andPollIdNotBetween(Integer value1, Integer value2) {
			addCriterion("poll_id not between", value1, value2, "pollId");
			return (Criteria) this;
		}

		public Criteria andChoiceTextIsNull() {
			addCriterion("choice_text is null");
			return (Criteria) this;
		}

		public Criteria andChoiceTextIsNotNull() {
			addCriterion("choice_text is not null");
			return (Criteria) this;
		}

		public Criteria andChoiceTextEqualTo(String value) {
			addCriterion("choice_text =", value, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextNotEqualTo(String value) {
			addCriterion("choice_text <>", value, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextGreaterThan(String value) {
			addCriterion("choice_text >", value, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextGreaterThanOrEqualTo(String value) {
			addCriterion("choice_text >=", value, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextLessThan(String value) {
			addCriterion("choice_text <", value, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextLessThanOrEqualTo(String value) {
			addCriterion("choice_text <=", value, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextLike(String value) {
			addCriterion("choice_text like", value, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextNotLike(String value) {
			addCriterion("choice_text not like", value, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextIn(List<String> values) {
			addCriterion("choice_text in", values, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextNotIn(List<String> values) {
			addCriterion("choice_text not in", values, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextBetween(String value1, String value2) {
			addCriterion("choice_text between", value1, value2, "choiceText");
			return (Criteria) this;
		}

		public Criteria andChoiceTextNotBetween(String value1, String value2) {
			addCriterion("choice_text not between", value1, value2, "choiceText");
			return (Criteria) this;
		}

		public Criteria andActiveFlagIsNull() {
			addCriterion("active_flag is null");
			return (Criteria) this;
		}

		public Criteria andActiveFlagIsNotNull() {
			addCriterion("active_flag is not null");
			return (Criteria) this;
		}

		public Criteria andActiveFlagEqualTo(Boolean value) {
			addCriterion("active_flag =", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagNotEqualTo(Boolean value) {
			addCriterion("active_flag <>", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagGreaterThan(Boolean value) {
			addCriterion("active_flag >", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagGreaterThanOrEqualTo(Boolean value) {
			addCriterion("active_flag >=", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagLessThan(Boolean value) {
			addCriterion("active_flag <", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagLessThanOrEqualTo(Boolean value) {
			addCriterion("active_flag <=", value, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagIn(List<Boolean> values) {
			addCriterion("active_flag in", values, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagNotIn(List<Boolean> values) {
			addCriterion("active_flag not in", values, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagBetween(Boolean value1, Boolean value2) {
			addCriterion("active_flag between", value1, value2, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andActiveFlagNotBetween(Boolean value1, Boolean value2) {
			addCriterion("active_flag not between", value1, value2, "activeFlag");
			return (Criteria) this;
		}

		public Criteria andVotesIsNull() {
			addCriterion("votes is null");
			return (Criteria) this;
		}

		public Criteria andVotesIsNotNull() {
			addCriterion("votes is not null");
			return (Criteria) this;
		}

		public Criteria andVotesEqualTo(Integer value) {
			addCriterion("votes =", value, "votes");
			return (Criteria) this;
		}

		public Criteria andVotesNotEqualTo(Integer value) {
			addCriterion("votes <>", value, "votes");
			return (Criteria) this;
		}

		public Criteria andVotesGreaterThan(Integer value) {
			addCriterion("votes >", value, "votes");
			return (Criteria) this;
		}

		public Criteria andVotesGreaterThanOrEqualTo(Integer value) {
			addCriterion("votes >=", value, "votes");
			return (Criteria) this;
		}

		public Criteria andVotesLessThan(Integer value) {
			addCriterion("votes <", value, "votes");
			return (Criteria) this;
		}

		public Criteria andVotesLessThanOrEqualTo(Integer value) {
			addCriterion("votes <=", value, "votes");
			return (Criteria) this;
		}

		public Criteria andVotesIn(List<Integer> values) {
			addCriterion("votes in", values, "votes");
			return (Criteria) this;
		}

		public Criteria andVotesNotIn(List<Integer> values) {
			addCriterion("votes not in", values, "votes");
			return (Criteria) this;
		}

		public Criteria andVotesBetween(Integer value1, Integer value2) {
			addCriterion("votes between", value1, value2, "votes");
			return (Criteria) this;
		}

		public Criteria andVotesNotBetween(Integer value1, Integer value2) {
			addCriterion("votes not between", value1, value2, "votes");
			return (Criteria) this;
		}

		public Criteria andMigrationHashIsNull() {
			addCriterion("migration_hash is null");
			return (Criteria) this;
		}

		public Criteria andMigrationHashIsNotNull() {
			addCriterion("migration_hash is not null");
			return (Criteria) this;
		}

		public Criteria andMigrationHashEqualTo(String value) {
			addCriterion("migration_hash =", value, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashNotEqualTo(String value) {
			addCriterion("migration_hash <>", value, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashGreaterThan(String value) {
			addCriterion("migration_hash >", value, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashGreaterThanOrEqualTo(String value) {
			addCriterion("migration_hash >=", value, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashLessThan(String value) {
			addCriterion("migration_hash <", value, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashLessThanOrEqualTo(String value) {
			addCriterion("migration_hash <=", value, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashLike(String value) {
			addCriterion("migration_hash like", value, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashNotLike(String value) {
			addCriterion("migration_hash not like", value, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashIn(List<String> values) {
			addCriterion("migration_hash in", values, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashNotIn(List<String> values) {
			addCriterion("migration_hash not in", values, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashBetween(String value1, String value2) {
			addCriterion("migration_hash between", value1, value2, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andMigrationHashNotBetween(String value1, String value2) {
			addCriterion("migration_hash not between", value1, value2, "migrationHash");
			return (Criteria) this;
		}

		public Criteria andCreatedTsIsNull() {
			addCriterion("created_ts is null");
			return (Criteria) this;
		}

		public Criteria andCreatedTsIsNotNull() {
			addCriterion("created_ts is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedTsEqualTo(LocalDateTime value) {
			addCriterion("created_ts =", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsNotEqualTo(LocalDateTime value) {
			addCriterion("created_ts <>", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsGreaterThan(LocalDateTime value) {
			addCriterion("created_ts >", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("created_ts >=", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsLessThan(LocalDateTime value) {
			addCriterion("created_ts <", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("created_ts <=", value, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsIn(List<LocalDateTime> values) {
			addCriterion("created_ts in", values, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsNotIn(List<LocalDateTime> values) {
			addCriterion("created_ts not in", values, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("created_ts between", value1, value2, "createdTs");
			return (Criteria) this;
		}

		public Criteria andCreatedTsNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("created_ts not between", value1, value2, "createdTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsIsNull() {
			addCriterion("updated_ts is null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsIsNotNull() {
			addCriterion("updated_ts is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsEqualTo(LocalDateTime value) {
			addCriterion("updated_ts =", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsNotEqualTo(LocalDateTime value) {
			addCriterion("updated_ts <>", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsGreaterThan(LocalDateTime value) {
			addCriterion("updated_ts >", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsGreaterThanOrEqualTo(LocalDateTime value) {
			addCriterion("updated_ts >=", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsLessThan(LocalDateTime value) {
			addCriterion("updated_ts <", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsLessThanOrEqualTo(LocalDateTime value) {
			addCriterion("updated_ts <=", value, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsIn(List<LocalDateTime> values) {
			addCriterion("updated_ts in", values, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsNotIn(List<LocalDateTime> values) {
			addCriterion("updated_ts not in", values, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("updated_ts between", value1, value2, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andUpdatedTsNotBetween(LocalDateTime value1, LocalDateTime value2) {
			addCriterion("updated_ts not between", value1, value2, "updatedTs");
			return (Criteria) this;
		}

		public Criteria andSeqnoIsNull() {
			addCriterion("seqno is null");
			return (Criteria) this;
		}

		public Criteria andSeqnoIsNotNull() {
			addCriterion("seqno is not null");
			return (Criteria) this;
		}

		public Criteria andSeqnoEqualTo(Integer value) {
			addCriterion("seqno =", value, "seqno");
			return (Criteria) this;
		}

		public Criteria andSeqnoNotEqualTo(Integer value) {
			addCriterion("seqno <>", value, "seqno");
			return (Criteria) this;
		}

		public Criteria andSeqnoGreaterThan(Integer value) {
			addCriterion("seqno >", value, "seqno");
			return (Criteria) this;
		}

		public Criteria andSeqnoGreaterThanOrEqualTo(Integer value) {
			addCriterion("seqno >=", value, "seqno");
			return (Criteria) this;
		}

		public Criteria andSeqnoLessThan(Integer value) {
			addCriterion("seqno <", value, "seqno");
			return (Criteria) this;
		}

		public Criteria andSeqnoLessThanOrEqualTo(Integer value) {
			addCriterion("seqno <=", value, "seqno");
			return (Criteria) this;
		}

		public Criteria andSeqnoIn(List<Integer> values) {
			addCriterion("seqno in", values, "seqno");
			return (Criteria) this;
		}

		public Criteria andSeqnoNotIn(List<Integer> values) {
			addCriterion("seqno not in", values, "seqno");
			return (Criteria) this;
		}

		public Criteria andSeqnoBetween(Integer value1, Integer value2) {
			addCriterion("seqno between", value1, value2, "seqno");
			return (Criteria) this;
		}

		public Criteria andSeqnoNotBetween(Integer value1, Integer value2) {
			addCriterion("seqno not between", value1, value2, "seqno");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table zfgbb.poll_choice
	 * @mbg.generated  Sun Oct 19 21:58:51 EDT 2025
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zfgbb.poll_choice
     *
     * @mbg.generated do_not_delete_during_merge Sun Oct 19 20:30:55 EDT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}