package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;
import java.util.Date;

public class PollDbo extends AbstractPostgresDb {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.poll_id
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Integer pollId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.poll_question
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private String pollQuestion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.thread_id
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Integer threadId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.created_ts
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.updated_ts
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.voting_locked_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Boolean votingLockedFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.expire_time
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private LocalDateTime expireTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.hide_results_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Boolean hideResultsFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.change_vote_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Boolean changeVoteFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.created_user_id
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Integer createdUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.guest_vote_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Boolean guestVoteFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.guest_vote_count
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Integer guestVoteCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.reset_poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Integer resetPoll;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.max_votes
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private Integer maxVotes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.migration_hash
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private String migrationHash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.poll.answer_text
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	private String answerText;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.poll_id
	 * @return  the value of zfgbb.poll.poll_id
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Integer getPollId() {
		return pollId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.poll_id
	 * @param pollId  the value for zfgbb.poll.poll_id
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setPollId(Integer pollId) {
		this.pollId = pollId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.poll_question
	 * @return  the value of zfgbb.poll.poll_question
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public String getPollQuestion() {
		return pollQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.poll_question
	 * @param pollQuestion  the value for zfgbb.poll.poll_question
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setPollQuestion(String pollQuestion) {
		this.pollQuestion = pollQuestion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.thread_id
	 * @return  the value of zfgbb.poll.thread_id
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Integer getThreadId() {
		return threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.thread_id
	 * @param threadId  the value for zfgbb.poll.thread_id
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setThreadId(Integer threadId) {
		this.threadId = threadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.created_ts
	 * @return  the value of zfgbb.poll.created_ts
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.created_ts
	 * @param createdTs  the value for zfgbb.poll.created_ts
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.updated_ts
	 * @return  the value of zfgbb.poll.updated_ts
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.updated_ts
	 * @param updatedTs  the value for zfgbb.poll.updated_ts
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.voting_locked_flag
	 * @return  the value of zfgbb.poll.voting_locked_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Boolean getVotingLockedFlag() {
		return votingLockedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.voting_locked_flag
	 * @param votingLockedFlag  the value for zfgbb.poll.voting_locked_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setVotingLockedFlag(Boolean votingLockedFlag) {
		this.votingLockedFlag = votingLockedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.expire_time
	 * @return  the value of zfgbb.poll.expire_time
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public LocalDateTime getExpireTime() {
		return expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.expire_time
	 * @param expireTime  the value for zfgbb.poll.expire_time
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setExpireTime(LocalDateTime expireTime) {
		this.expireTime = expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.hide_results_flag
	 * @return  the value of zfgbb.poll.hide_results_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Boolean getHideResultsFlag() {
		return hideResultsFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.hide_results_flag
	 * @param hideResultsFlag  the value for zfgbb.poll.hide_results_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setHideResultsFlag(Boolean hideResultsFlag) {
		this.hideResultsFlag = hideResultsFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.change_vote_flag
	 * @return  the value of zfgbb.poll.change_vote_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Boolean getChangeVoteFlag() {
		return changeVoteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.change_vote_flag
	 * @param changeVoteFlag  the value for zfgbb.poll.change_vote_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setChangeVoteFlag(Boolean changeVoteFlag) {
		this.changeVoteFlag = changeVoteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.created_user_id
	 * @return  the value of zfgbb.poll.created_user_id
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Integer getCreatedUserId() {
		return createdUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.created_user_id
	 * @param createdUserId  the value for zfgbb.poll.created_user_id
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setCreatedUserId(Integer createdUserId) {
		this.createdUserId = createdUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.guest_vote_flag
	 * @return  the value of zfgbb.poll.guest_vote_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Boolean getGuestVoteFlag() {
		return guestVoteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.guest_vote_flag
	 * @param guestVoteFlag  the value for zfgbb.poll.guest_vote_flag
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setGuestVoteFlag(Boolean guestVoteFlag) {
		this.guestVoteFlag = guestVoteFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.guest_vote_count
	 * @return  the value of zfgbb.poll.guest_vote_count
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Integer getGuestVoteCount() {
		return guestVoteCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.guest_vote_count
	 * @param guestVoteCount  the value for zfgbb.poll.guest_vote_count
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setGuestVoteCount(Integer guestVoteCount) {
		this.guestVoteCount = guestVoteCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.reset_poll
	 * @return  the value of zfgbb.poll.reset_poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Integer getResetPoll() {
		return resetPoll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.reset_poll
	 * @param resetPoll  the value for zfgbb.poll.reset_poll
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setResetPoll(Integer resetPoll) {
		this.resetPoll = resetPoll;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.max_votes
	 * @return  the value of zfgbb.poll.max_votes
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public Integer getMaxVotes() {
		return maxVotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.max_votes
	 * @param maxVotes  the value for zfgbb.poll.max_votes
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setMaxVotes(Integer maxVotes) {
		this.maxVotes = maxVotes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.migration_hash
	 * @return  the value of zfgbb.poll.migration_hash
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.migration_hash
	 * @param migrationHash  the value for zfgbb.poll.migration_hash
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.poll.answer_text
	 * @return  the value of zfgbb.poll.answer_text
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public String getAnswerText() {
		return answerText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.poll.answer_text
	 * @param answerText  the value for zfgbb.poll.answer_text
	 * @mbg.generated  Wed Nov 26 12:08:11 EST 2025
	 */
	public void setAnswerText(String answerText) {
		this.answerText = answerText;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal(this.pollQuestion +
			   this.createdUserId.toString() +
			   this.guestVoteCount.toString() +
			   this.pollId.toString() +
			   this.resetPoll.toString() +
			   this.threadId.toString() +
			   this.changeVoteFlag.toString() +
			   (this.expireTime == null ? "0" : this.expireTime.toString()) +
			   this.guestVoteFlag.toString() +
			   this.hideResultsFlag.toString() +
			   this.maxVotes.toString() +
			   this.pollQuestion +
			   this.votingLockedFlag.toString());
	}
}