package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;
import java.time.LocalDate;
import java.util.Date;

public class UserBioInfoDbo extends AbstractPostgresDb {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.user_id
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.custom_title
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private String customTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.personal_text
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private String personalText;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.created_ts
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.updated_ts
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.signature
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private String signature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.migration_hash
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private String migrationHash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.avatar_id
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private Integer avatarId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.date_registered
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private Date dateRegistered;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.last_login
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private Date lastLogin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.real_name
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.birth_date
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private LocalDate birthDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.website_title
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private String websiteTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.website_url
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private String websiteUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.location
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private String location;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.time_format
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private String timeFormat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.karma_good
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private Integer karmaGood;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.karma_bad
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private Integer karmaBad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.hide_email_flag
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private Boolean hideEmailFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.hide_online_status
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private Boolean hideOnlineStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_bio_info.gender_id
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	private Integer genderId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.user_id
	 * @return  the value of zfgbb.user_bio_info.user_id
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.user_id
	 * @param userId  the value for zfgbb.user_bio_info.user_id
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.custom_title
	 * @return  the value of zfgbb.user_bio_info.custom_title
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public String getCustomTitle() {
		return customTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.custom_title
	 * @param customTitle  the value for zfgbb.user_bio_info.custom_title
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setCustomTitle(String customTitle) {
		this.customTitle = customTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.personal_text
	 * @return  the value of zfgbb.user_bio_info.personal_text
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public String getPersonalText() {
		return personalText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.personal_text
	 * @param personalText  the value for zfgbb.user_bio_info.personal_text
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setPersonalText(String personalText) {
		this.personalText = personalText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.created_ts
	 * @return  the value of zfgbb.user_bio_info.created_ts
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.created_ts
	 * @param createdTs  the value for zfgbb.user_bio_info.created_ts
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.updated_ts
	 * @return  the value of zfgbb.user_bio_info.updated_ts
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.updated_ts
	 * @param updatedTs  the value for zfgbb.user_bio_info.updated_ts
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.signature
	 * @return  the value of zfgbb.user_bio_info.signature
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public String getSignature() {
		return signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.signature
	 * @param signature  the value for zfgbb.user_bio_info.signature
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setSignature(String signature) {
		this.signature = signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.migration_hash
	 * @return  the value of zfgbb.user_bio_info.migration_hash
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.migration_hash
	 * @param migrationHash  the value for zfgbb.user_bio_info.migration_hash
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.avatar_id
	 * @return  the value of zfgbb.user_bio_info.avatar_id
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public Integer getAvatarId() {
		return avatarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.avatar_id
	 * @param avatarId  the value for zfgbb.user_bio_info.avatar_id
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setAvatarId(Integer avatarId) {
		this.avatarId = avatarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.date_registered
	 * @return  the value of zfgbb.user_bio_info.date_registered
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public Date getDateRegistered() {
		return dateRegistered;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.date_registered
	 * @param dateRegistered  the value for zfgbb.user_bio_info.date_registered
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setDateRegistered(Date dateRegistered) {
		this.dateRegistered = dateRegistered;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.last_login
	 * @return  the value of zfgbb.user_bio_info.last_login
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public Date getLastLogin() {
		return lastLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.last_login
	 * @param lastLogin  the value for zfgbb.user_bio_info.last_login
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.real_name
	 * @return  the value of zfgbb.user_bio_info.real_name
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.real_name
	 * @param realName  the value for zfgbb.user_bio_info.real_name
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.birth_date
	 * @return  the value of zfgbb.user_bio_info.birth_date
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public LocalDate getBirthDate() {
		return birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.birth_date
	 * @param birthDate  the value for zfgbb.user_bio_info.birth_date
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setBirthDate(LocalDate birthDate) {
		this.birthDate = birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.website_title
	 * @return  the value of zfgbb.user_bio_info.website_title
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public String getWebsiteTitle() {
		return websiteTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.website_title
	 * @param websiteTitle  the value for zfgbb.user_bio_info.website_title
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setWebsiteTitle(String websiteTitle) {
		this.websiteTitle = websiteTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.website_url
	 * @return  the value of zfgbb.user_bio_info.website_url
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public String getWebsiteUrl() {
		return websiteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.website_url
	 * @param websiteUrl  the value for zfgbb.user_bio_info.website_url
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.location
	 * @return  the value of zfgbb.user_bio_info.location
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public String getLocation() {
		return location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.location
	 * @param location  the value for zfgbb.user_bio_info.location
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.time_format
	 * @return  the value of zfgbb.user_bio_info.time_format
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public String getTimeFormat() {
		return timeFormat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.time_format
	 * @param timeFormat  the value for zfgbb.user_bio_info.time_format
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setTimeFormat(String timeFormat) {
		this.timeFormat = timeFormat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.karma_good
	 * @return  the value of zfgbb.user_bio_info.karma_good
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public Integer getKarmaGood() {
		return karmaGood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.karma_good
	 * @param karmaGood  the value for zfgbb.user_bio_info.karma_good
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setKarmaGood(Integer karmaGood) {
		this.karmaGood = karmaGood;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.karma_bad
	 * @return  the value of zfgbb.user_bio_info.karma_bad
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public Integer getKarmaBad() {
		return karmaBad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.karma_bad
	 * @param karmaBad  the value for zfgbb.user_bio_info.karma_bad
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setKarmaBad(Integer karmaBad) {
		this.karmaBad = karmaBad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.hide_email_flag
	 * @return  the value of zfgbb.user_bio_info.hide_email_flag
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public Boolean getHideEmailFlag() {
		return hideEmailFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.hide_email_flag
	 * @param hideEmailFlag  the value for zfgbb.user_bio_info.hide_email_flag
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setHideEmailFlag(Boolean hideEmailFlag) {
		this.hideEmailFlag = hideEmailFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.hide_online_status
	 * @return  the value of zfgbb.user_bio_info.hide_online_status
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public Boolean getHideOnlineStatus() {
		return hideOnlineStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.hide_online_status
	 * @param hideOnlineStatus  the value for zfgbb.user_bio_info.hide_online_status
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setHideOnlineStatus(Boolean hideOnlineStatus) {
		this.hideOnlineStatus = hideOnlineStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_bio_info.gender_id
	 * @return  the value of zfgbb.user_bio_info.gender_id
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public Integer getGenderId() {
		return genderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_bio_info.gender_id
	 * @param genderId  the value for zfgbb.user_bio_info.gender_id
	 * @mbg.generated  Sun Sep 21 17:46:20 EDT 2025
	 */
	public void setGenderId(Integer genderId) {
		this.genderId = genderId;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal((userId.toString() 
										  + (signature != null ? signature : "") 
										  + (customTitle != null ? customTitle : "") 
										  + (avatarId != null ? avatarId : "")
										  + (personalText != null ? personalText : "")))
										  + (karmaGood != null ? karmaGood : "")
										  + (karmaBad != null ? karmaBad : "")
										  + (hideOnlineStatus != null ? hideOnlineStatus.toString() : "")
										  + (hideEmailFlag != null ? hideEmailFlag.toString() : "")
										  + (birthDate.toString())
										  + (genderId != null ? genderId.toString() : "");
												  
	}
}