package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

public class UserNotifSettingsDbo extends AbstractPostgresDb {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_notif_settings.user_id
	 * @mbg.generated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_notif_settings.notify_announcements_flag
	 * @mbg.generated
	 */
	private Boolean notifyAnnouncementsFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_notif_settings.notify_send_body_flag
	 * @mbg.generated
	 */
	private Boolean notifySendBodyFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_notif_settings.send_happy_birthday_flag
	 * @mbg.generated
	 */
	private Boolean sendHappyBirthdayFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_notif_settings.created_ts
	 * @mbg.generated
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_notif_settings.updated_ts
	 * @mbg.generated
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_notif_settings.migration_hash
	 * @mbg.generated
	 */
	private String migrationHash;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_notif_settings.user_id
	 * @return  the value of zfgbb.user_notif_settings.user_id
	 * @mbg.generated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_notif_settings.user_id
	 * @param userId  the value for zfgbb.user_notif_settings.user_id
	 * @mbg.generated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_notif_settings.notify_announcements_flag
	 * @return  the value of zfgbb.user_notif_settings.notify_announcements_flag
	 * @mbg.generated
	 */
	public Boolean getNotifyAnnouncementsFlag() {
		return notifyAnnouncementsFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_notif_settings.notify_announcements_flag
	 * @param notifyAnnouncementsFlag  the value for zfgbb.user_notif_settings.notify_announcements_flag
	 * @mbg.generated
	 */
	public void setNotifyAnnouncementsFlag(Boolean notifyAnnouncementsFlag) {
		this.notifyAnnouncementsFlag = notifyAnnouncementsFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_notif_settings.notify_send_body_flag
	 * @return  the value of zfgbb.user_notif_settings.notify_send_body_flag
	 * @mbg.generated
	 */
	public Boolean getNotifySendBodyFlag() {
		return notifySendBodyFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_notif_settings.notify_send_body_flag
	 * @param notifySendBodyFlag  the value for zfgbb.user_notif_settings.notify_send_body_flag
	 * @mbg.generated
	 */
	public void setNotifySendBodyFlag(Boolean notifySendBodyFlag) {
		this.notifySendBodyFlag = notifySendBodyFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_notif_settings.send_happy_birthday_flag
	 * @return  the value of zfgbb.user_notif_settings.send_happy_birthday_flag
	 * @mbg.generated
	 */
	public Boolean getSendHappyBirthdayFlag() {
		return sendHappyBirthdayFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_notif_settings.send_happy_birthday_flag
	 * @param sendHappyBirthdayFlag  the value for zfgbb.user_notif_settings.send_happy_birthday_flag
	 * @mbg.generated
	 */
	public void setSendHappyBirthdayFlag(Boolean sendHappyBirthdayFlag) {
		this.sendHappyBirthdayFlag = sendHappyBirthdayFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_notif_settings.created_ts
	 * @return  the value of zfgbb.user_notif_settings.created_ts
	 * @mbg.generated
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_notif_settings.created_ts
	 * @param createdTs  the value for zfgbb.user_notif_settings.created_ts
	 * @mbg.generated
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_notif_settings.updated_ts
	 * @return  the value of zfgbb.user_notif_settings.updated_ts
	 * @mbg.generated
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_notif_settings.updated_ts
	 * @param updatedTs  the value for zfgbb.user_notif_settings.updated_ts
	 * @mbg.generated
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_notif_settings.migration_hash
	 * @return  the value of zfgbb.user_notif_settings.migration_hash
	 * @mbg.generated
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_notif_settings.migration_hash
	 * @param migrationHash  the value for zfgbb.user_notif_settings.migration_hash
	 * @mbg.generated
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		// TODO: Implement hash computation based on key fields
		return null;
	}
} 