package com.zfgc.zfgbb.migrator.db;

import java.security.NoSuchAlgorithmException;
import java.time.LocalDateTime;

import lombok.Builder;

@Builder
public class UserPollChoiceDbo extends AbstractPostgresDb{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_poll_choice.user_poll_choice_id
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	private Integer userPollChoiceId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_poll_choice.user_id
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_poll_choice.created_ts
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	private LocalDateTime createdTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_poll_choice.updated_ts
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	private LocalDateTime updatedTs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_poll_choice.migration_hash
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	private String migrationHash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column zfgbb.user_poll_choice.poll_choice_id
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	private Integer pollChoiceId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_poll_choice.user_poll_choice_id
	 * @return  the value of zfgbb.user_poll_choice.user_poll_choice_id
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public Integer getUserPollChoiceId() {
		return userPollChoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_poll_choice.user_poll_choice_id
	 * @param userPollChoiceId  the value for zfgbb.user_poll_choice.user_poll_choice_id
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public void setUserPollChoiceId(Integer userPollChoiceId) {
		this.userPollChoiceId = userPollChoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_poll_choice.user_id
	 * @return  the value of zfgbb.user_poll_choice.user_id
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_poll_choice.user_id
	 * @param userId  the value for zfgbb.user_poll_choice.user_id
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_poll_choice.created_ts
	 * @return  the value of zfgbb.user_poll_choice.created_ts
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public LocalDateTime getCreatedTs() {
		return createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_poll_choice.created_ts
	 * @param createdTs  the value for zfgbb.user_poll_choice.created_ts
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public void setCreatedTs(LocalDateTime createdTs) {
		this.createdTs = createdTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_poll_choice.updated_ts
	 * @return  the value of zfgbb.user_poll_choice.updated_ts
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public LocalDateTime getUpdatedTs() {
		return updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_poll_choice.updated_ts
	 * @param updatedTs  the value for zfgbb.user_poll_choice.updated_ts
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public void setUpdatedTs(LocalDateTime updatedTs) {
		this.updatedTs = updatedTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_poll_choice.migration_hash
	 * @return  the value of zfgbb.user_poll_choice.migration_hash
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public String getMigrationHash() {
		return migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_poll_choice.migration_hash
	 * @param migrationHash  the value for zfgbb.user_poll_choice.migration_hash
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public void setMigrationHash(String migrationHash) {
		this.migrationHash = migrationHash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column zfgbb.user_poll_choice.poll_choice_id
	 * @return  the value of zfgbb.user_poll_choice.poll_choice_id
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public Integer getPollChoiceId() {
		return pollChoiceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column zfgbb.user_poll_choice.poll_choice_id
	 * @param pollChoiceId  the value for zfgbb.user_poll_choice.poll_choice_id
	 * @mbg.generated  Mon Oct 20 21:05:07 EDT 2025
	 */
	public void setPollChoiceId(Integer pollChoiceId) {
		this.pollChoiceId = pollChoiceId;
	}

	@Override
	public String computeHash() throws NoSuchAlgorithmException {
		return super.calculateHashInternal(
				this.pollChoiceId.toString() +
				this.userId.toString()
				);
	}
}